# Generated by Django 4.2.11 on 2026-04-14 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimiento',
            name='cantidad_entregada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='unidad_medida',
            field=models.CharField(choices=[('KILO', 'Kilo'), ('UNIDAD', 'Unidad')], default='KILO', max_length=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='unidad_medida',
            field=models.CharField(choices=[('KILO', 'Kilo'), ('UNIDAD', 'Unidad')], default='KILO', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_venta_base',
            field=models.CharField(choices=[('KILO', 'Kilo'), ('UNIDAD', 'Unidad'), ('AMBOS', 'Ambos')], default='KILO', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='cancelacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='detallemovimiento',
            index=models.Index(fields=['id_cliente'], name='idx_dm_cliente'),
        ),
        migrations.AddIndex(
            model_name='detallemovimiento',
            index=models.Index(fields=['id_jornada'], name='idx_dm_jornada'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['id_pedido'], name='idx_dp_pedido'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['id_cliente'], name='idx_pedido_cliente'),
        ),
        migrations.AddIndex(
            model_name='produccion',
            index=models.Index(fields=['id_jornada'], name='idx_prod_jornada'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('rut', 'digito_verificador'), name='unique_cliente_rut_dv'),
        ),
        migrations.AddConstraint(
            model_name='detallemovimiento',
            constraint=models.CheckConstraint(check=models.Q(('descuento_porcentaje_aplicado__gte', 0), ('descuento_porcentaje_aplicado__lte', 100)), name='check_descuento_detalle_movimiento'),
        ),
        migrations.AddConstraint(
            model_name='detallemovimiento',
            constraint=models.CheckConstraint(check=models.Q(('unidad_medida__in', ['KILO', 'UNIDAD'])), name='check_detalle_movimiento_unidad_medida'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(check=models.Q(('descuento_porcentaje_aplicado__gte', 0), ('descuento_porcentaje_aplicado__lte', 100)), name='check_descuento_detalle_pedido'),
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.CheckConstraint(check=models.Q(('unidad_medida__in', ['KILO', 'UNIDAD'])), name='check_detalle_pedido_unidad_medida'),
        ),
        migrations.AddConstraint(
            model_name='distribucion',
            constraint=models.UniqueConstraint(fields=('nombre_distribucion',), name='unique_distribucion_nombre'),
        ),
        migrations.AddConstraint(
            model_name='insumo',
            constraint=models.CheckConstraint(check=models.Q(('activo__in', ['S', 'N'])), name='check_insumo_activo'),
        ),
        migrations.AddConstraint(
            model_name='movimientobodega',
            constraint=models.CheckConstraint(check=models.Q(('tipo_movimiento__in', ['ENTRADA', 'SALIDA', 'AJUSTE'])), name='check_tipo_movimiento'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(check=models.Q(('unidad_venta_base__in', ['KILO', 'UNIDAD', 'AMBOS'])), name='check_producto_unidad_venta_base'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('nombre_turno',), name='unique_turno_nombre'),
        ),
    ]
