# Generated by Django 4.2.11 on 2026-04-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vistas_stock_y_controles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenClienteDia',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_cliente', models.BigIntegerField()),
                ('rut', models.IntegerField()),
                ('digito_verificador', models.CharField(max_length=1)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('venta_dia', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pago_dia', models.DecimalField(decimal_places=2, max_digits=20)),
                ('saldo_dia', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'vw_resumen_cliente_dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaldoAcumuladoCliente',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.BigIntegerField()),
                ('rut', models.IntegerField()),
                ('digito_verificador', models.CharField(max_length=1)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('saldo_acumulado', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'vw_saldo_acumulado_cliente',
                'managed': False,
            },
        ),
                migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE detalle_movimiento
                    DROP COLUMN IF EXISTS kilos CASCADE;
                    """,
                    reverse_sql="""
                    ALTER TABLE detalle_movimiento
                    ADD COLUMN IF NOT EXISTS kilos NUMERIC(10,2) DEFAULT 0 NOT NULL;
                    """,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="detallemovimiento",
                    name="kilos",
                ),
            ],
        ),
    ]