# Generated by Django 4.2.11 on 2026-04-26 05:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ajusta_funcion_rinde_pan_corriente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRepartoTurno',
            fields=[
                ('id_detalle_reparto_turno', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad_medida', models.CharField(choices=[('KILO', 'Kilo'), ('UNIDAD', 'Unidad')], default='KILO', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('id_distribucion', models.ForeignKey(db_column='id_distribucion', on_delete=django.db.models.deletion.CASCADE, to='api.distribucion')),
                ('id_jornada', models.ForeignKey(db_column='id_jornada', on_delete=django.db.models.deletion.CASCADE, to='api.jornadadiaria')),
                ('id_turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, to='api.turno')),
            ],
            options={
                'db_table': 'detalle_reparto_turno',
                'indexes': [models.Index(fields=['id_jornada'], name='idx_drt_jornada'), models.Index(fields=['id_turno'], name='idx_drt_turno'), models.Index(fields=['id_cliente'], name='idx_drt_cliente'), models.Index(fields=['id_distribucion'], name='idx_drt_distribucion')],
            },
        ),
        migrations.AddConstraint(
            model_name='detallerepartoturno',
            constraint=models.CheckConstraint(check=models.Q(('unidad_medida__in', ['KILO', 'UNIDAD'])), name='check_drt_unidad_medida'),
        ),
        migrations.AddConstraint(
            model_name='detallerepartoturno',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_entregada__gte', 0)), name='check_drt_cantidad_no_negativa'),
        ),
    ]
